[tool.poetry]
name = "console-bot"
version = "0.1.0"
description = "pet projevt console bot"
authors = ["Lara <dmilarisa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
